let
    // Replace this path with the local path generated by Power Query
    // after importing the CSV from your downloaded repository.
    SourceFilePath = "C:\path\to\Gaming_Academic_Performance_Analysis-Q1\data\gaming_academic_performance.csv",
    Source = Csv.Document(
        File.Contents(SourceFilePath),
        [Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.Csv]
    ),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),

    // Numeric columns use English (United States) locale so decimal points are read correctly.
    ChangedTypes = Table.TransformColumnTypes(
        PromotedHeaders,
        {
            {"student_id", Int64.Type},
            {"age", Int64.Type},
            {"gender", type text},
            {"gaming_hours", type number},
            {"study_hours", type number},
            {"sleep_hours", type number},
            {"attendance", type number},
            {"gaming_genre", type text},
            {"social_activity", type number},
            {"device_usage", type number},
            {"reaction_time_ms", type number},
            {"addiction_score", type number},
            {"stress_level", type text},
            {"grades", type number}
        },
        "en-US"
    ),

    TrimmedText = Table.TransformColumns(
        ChangedTypes,
        {
            {"gender", each Text.Proper(Text.Trim(_)), type text},
            {"stress_level", each Text.Proper(Text.Trim(_)), type text},
            {"gaming_genre", each Text.Trim(_), type text}
        }
    ),

    PreservedAcronyms = Table.TransformColumns(
        TrimmedText,
        {
            {
                "gaming_genre",
                each if Text.Lower(_) = "fps" then "FPS"
                     else if Text.Lower(_) = "rpg" then "RPG"
                     else Text.Proper(_),
                type text
            }
        }
    ),

    RoundedNumbers = Table.TransformColumns(
        PreservedAcronyms,
        {
            {"gaming_hours", each Number.Round(_, 2), type number},
            {"study_hours", each Number.Round(_, 2), type number},
            {"sleep_hours", each Number.Round(_, 2), type number},
            {"attendance", each Number.Round(_, 2), type number},
            {"social_activity", each Number.Round(_, 2), type number},
            {"device_usage", each Number.Round(_, 2), type number},
            {"reaction_time_ms", each Number.Round(_, 2), type number},
            {"addiction_score", each Number.Round(_, 2), type number},
            {"grades", each Number.Round(_, 2), type number}
        }
    ),

    RenamedAttendance = Table.RenameColumns(
        RoundedNumbers,
        {{"attendance", "attendance (%)"}}
    ),

    CappedGrades = Table.TransformColumns(
        RenamedAttendance,
        {{"grades", each if _ < 0 then 0 else if _ > 100 then 100 else _, type number}}
    ),
    FlooredAddictionScore = Table.TransformColumns(
        CappedGrades,
        {{"addiction_score", each if _ < 0 then 0 else _, type number}}
    ),

    AddedGamingBand = Table.AddColumn(
        FlooredAddictionScore,
        "gaming_band",
        each if [gaming_hours] <= 2 then "0-2h"
             else if [gaming_hours] <= 4 then "2-4h"
             else if [gaming_hours] <= 6 then "4-6h"
             else "6-8h",
        type text
    ),
    AddedStudyBand = Table.AddColumn(
        AddedGamingBand,
        "study_band",
        each if [study_hours] <= 3 then "1-3h"
             else if [study_hours] <= 6 then "3-6h"
             else if [study_hours] <= 8 then "6-8h"
             else "8-10h",
        type text
    ),
    AddedSleepBand = Table.AddColumn(
        AddedStudyBand,
        "sleep_band",
        each if [sleep_hours] < 5 then "<5h"
             else if [sleep_hours] < 7 then "5-7h"
             else if [sleep_hours] < 8 then "7-8h"
             else "8h+",
        type text
    ),
    AddedPerformanceBand = Table.AddColumn(
        AddedSleepBand,
        "performance_band",
        each if [grades] < 60 then "At Risk"
             else if [grades] < 75 then "Regular"
             else if [grades] < 90 then "Solid"
             else "Excellent",
        type text
    ),
    AddedRiskFlag = Table.AddColumn(
        AddedPerformanceBand,
        "risk_flag",
        each if [grades] < 60 and [gaming_hours] >= 6 then "High Risk: High Gaming"
             else if [grades] < 60 and [study_hours] < 3 then "High Risk: Low Study"
             else if [grades] < 60 then "Academic Risk"
             else "Monitor",
        type text
    )
in
    AddedRiskFlag
